### ISSUE TITLE
Convolution stage bug

### ISSUE THREAD

**Issue by EdisonL-S** [EdisonLam-USYD/Multi-Precision-CNN#1]
currently the convolution stage takes an additional cycle when adding padding to the buffer meaning. this can mean that it can potentially skip a, input and just replace it with 0.

**Comment by EdisonLam-USYD** [comment]
``

**Comment by EdisonL-S** [comment]
`out_ready` value denotes when the input should be given, hence alleviating the issue. This still does not fix the wasted clock cycle.

Future improvement required

**Comment by EdisonL-S** [comment]
New convolution buffer function fixes this issue.
